### ISSUE TITLE
App crashes on first launch after giving permission to use location

### ISSUE THREAD

**Issue by JohnBehnke** [wtg/RPI_Tours_iOS#34]
App crashes at `let userLocation: CLLocationCoordinate2D = (self.locationManager.location?.coordinate)!` in `SelectedTourViewController.calculateDirections()` when the app is run for the first time on a device

**Comment by jacobspeicher** [comment]
Just pushed a commit to New-Info-Screen to try and fix this, just checked that `self.locationManager.location` wasn't nil before I did all the userLocation stuff. Works on my phone now, but needs more testing.
